import os
import sys

# Ensure backend directory is in the python path
backend_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
if backend_dir not in sys.path:
    sys.path.insert(0, backend_dir)

from app.core.database import Base
from app.models import *  # Ensure all models are registered

def get_mermaid_type(column_type):
    type_str = str(column_type).upper()
    if 'VARCHAR' in type_str or 'TEXT' in type_str or 'STRING' in type_str or 'CHAR' in type_str:
        return 'string'
    elif 'INT' in type_str:
        return 'int'
    elif 'FLOAT' in type_str or 'DECIMAL' in type_str or 'NUMERIC' in type_str:
        return 'float'
    elif 'BOOL' in type_str:
        return 'boolean'
    elif 'TIMESTAMP' in type_str or 'DATETIME' in type_str:
        return 'datetime'
    elif 'DATE' in type_str:
        return 'date'
    elif 'JSON' in type_str:
        return 'json'
    else:
        return type_str.split('(')[0]

def generate_schema_markdown():
    tables = Base.metadata.tables
    
    lines = []
    lines.append("# Database Schema")
    lines.append("")
    lines.append("This document is auto-generated by `backend/scripts/generate_schema_doc.py` whenever a database migration is run.")
    lines.append("")
    lines.append("## Entity-Relationship Diagram")
    lines.append("")
    lines.append("```mermaid")
    lines.append("erDiagram")
    
    # 1. Add Tables and Columns
    for table_name, table in tables.items():
        lines.append(f"    {table_name} {{")
        for column in table.columns:
            col_type = get_mermaid_type(column.type)
            constraints = []
            if column.primary_key:
                constraints.append("PK")
            elif column.foreign_keys:
                constraints.append("FK")
            elif column.unique:
                constraints.append("UK")
            
            constraint_str = " ".join(constraints) if constraints else ""
            # Mermaid doesn't like spaces in type names, so strip them
            safe_type = col_type.replace(" ", "_").replace("(", "").replace(")", "").replace("[", "").replace("]", "")
            if not safe_type:
                safe_type = "unknown"
            
            # Use quotes if column name conflicts with mermaid keywords, but simple names are fine
            col_name = column.name
            lines.append(f"        {safe_type} {col_name} {constraint_str}")
        lines.append("    }")
    
    lines.append("")
    
    # 2. Add Relationships
    for table_name, table in tables.items():
        for column in table.columns:
            for fk in column.foreign_keys:
                target_table = fk.column.table.name
                # Many-to-one since foreign key is on the many side
                lines.append(f"    {table_name} }}|--|| {target_table} : \"{column.name}\"")
                
    lines.append("```")
    lines.append("")
    
    # 3. Add Indices Section
    lines.append("## Indices & Constraints")
    lines.append("")
    for table_name, table in tables.items():
        has_indices = len(table.indexes) > 0 or any(c.unique and not c.primary_key for c in table.columns)
        if has_indices:
            lines.append(f"### `{table_name}`")
            for idx in table.indexes:
                cols = ", ".join([c.name for c in idx.columns])
                lines.append(f"- **Index**: `{idx.name}` on columns: ({cols})")
            for c in table.columns:
                if c.unique and not c.primary_key:
                    lines.append(f"- **Unique**: `{c.name}`")
            lines.append("")

    return "\n".join(lines)

def generate_schema_html(mermaid_content):
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Database Schema Diagram</title>
    <script src="https://cdn.jsdelivr.net/npm/svg-pan-zoom@3.6.1/dist/svg-pan-zoom.min.js"></script>
    <style>
        body {{ font-family: sans-serif; margin: 0; padding: 0; background-color: #f9f9f9; overflow: hidden; }}
        h1 {{ text-align: center; margin-top: 20px; }}
        .mermaid-container {{ 
            width: 100vw; 
            height: calc(100vh - 100px);
            background: white; 
            box-shadow: 0 -4px 6px rgba(0,0,0,0.1); 
            display: flex;
            justify-content: center;
            align-items: center;
        }}
        #mermaid-svg {{ width: 100%; height: 100%; }}
        .hint {{ text-align: center; color: #666; margin-bottom: 20px; }}
        /* Hide raw mermaid code before render */
        #raw-mermaid {{ display: none; }}
    </style>
</head>
<body>
    <h1>Database Schema Diagram</h1>
    <p class="hint">Use your mouse wheel to zoom, and click and drag to pan.</p>
    <div class="mermaid-container" id="container">
        <!-- Rendered SVG will go here -->
    </div>
    
    <div id="raw-mermaid">
{mermaid_content}
    </div>

    <script type="module">
        import mermaid from 'https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.esm.min.mjs';
        
        mermaid.initialize({{ 
            startOnLoad: false, 
            theme: 'default',
            securityLevel: 'loose',
            er: {{ useMaxWidth: false }} 
        }});

        async function renderDiagram() {{
            const code = document.getElementById('raw-mermaid').textContent.trim();
            const container = document.getElementById('container');
            try {{
                const {{ svg }} = await mermaid.render('mermaid-svg', code);
                container.innerHTML = svg;
                
                // Initialize pan and zoom
                const svgElement = document.getElementById('mermaid-svg');
                svgPanZoom(svgElement, {{
                    zoomEnabled: true,
                    controlIconsEnabled: true,
                    fit: true,
                    center: true,
                    minZoom: 0.1,
                    maxZoom: 10
                }});
            }} catch (err) {{
                console.error('Mermaid rendering failed', err);
            }}
        }}
        
        renderDiagram();
    </script>
</body>
</html>"""

def main():
    docs_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..', 'Docs'))
    os.makedirs(docs_dir, exist_ok=True)
    
    # Generate Markdown
    md_output_path = os.path.join(docs_dir, 'database-schema.md')
    markdown_content = generate_schema_markdown()
    
    with open(md_output_path, 'w', encoding='utf-8') as f:
        f.write(markdown_content)
        
    # Generate HTML
    html_output_path = os.path.join(docs_dir, 'database-schema.html')
    # Extract just the mermaid block for the HTML
    mermaid_block = ""
    in_mermaid = False
    for line in markdown_content.split('\n'):
        if line.startswith("```mermaid"):
            in_mermaid = True
            continue
        elif line.startswith("```") and in_mermaid:
            in_mermaid = False
            continue
        
        if in_mermaid:
            mermaid_block += line + "\n"
            
    html_content = generate_schema_html(mermaid_block)
    
    with open(html_output_path, 'w', encoding='utf-8') as f:
        f.write(html_content)
        
    print(f"Successfully generated database schema document at {md_output_path} and {html_output_path}")

if __name__ == "__main__":
    main()
