"""add_missing_model_tables

Revision ID: 0b4b1c3739b4
Revises: a1b2c3d4e5f7
Create Date: 2026-05-29 17:57:26.015235

All CREATE TABLE and CREATE INDEX statements use IF NOT EXISTS so that this
migration is idempotent on production databases where these tables and indexes
were created outside of Alembic before migration tracking was introduced.

Tables added:
  futures_contracts, futures_rollovers, journal_entries, tags, stock_metrics,
  trade_executions, trade_tags

Indexes added to existing tables:
  ix_market_holidays_id, ix_ticker_references_ticker,
  ix_trades_* (id, symbol, status, side, open_date, close_date)

universe_quality_reports: the autogenerated UNIQUE constraint on universe_id
  is replaced by a unique index (matches the SQLAlchemy model's index=True +
  unique=True combination).
"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '0b4b1c3739b4'
down_revision: Union[str, None] = 'a1b2c3d4e5f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ── futures_contracts ────────────────────────────────────────────────────
    op.execute("""
        CREATE TABLE IF NOT EXISTS futures_contracts (
            id              SERIAL          NOT NULL,
            symbol          VARCHAR(20)     NOT NULL,
            exchange        VARCHAR(20)     NOT NULL,
            contract_month  VARCHAR(8)      NOT NULL,
            expiry_date     DATE,
            con_id          INTEGER,
            is_expired      BOOLEAN,
            data_downloaded BOOLEAN,
            last_bar_date   TIMESTAMP,
            first_bar_date  TIMESTAMP,
            created_at      TIMESTAMP,
            last_updated    TIMESTAMP,
            PRIMARY KEY (id)
        )
    """)
    op.execute("CREATE INDEX IF NOT EXISTS idx_fc_symbol_exchange ON futures_contracts (symbol, exchange)")
    op.execute("CREATE UNIQUE INDEX IF NOT EXISTS idx_fc_symbol_month ON futures_contracts (symbol, contract_month)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_futures_contracts_id ON futures_contracts (id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_futures_contracts_symbol ON futures_contracts (symbol)")

    # ── futures_rollovers ────────────────────────────────────────────────────
    op.execute("""
        CREATE TABLE IF NOT EXISTS futures_rollovers (
            id               SERIAL      NOT NULL,
            symbol           VARCHAR(20) NOT NULL,
            exchange         VARCHAR(20) NOT NULL,
            from_contract    VARCHAR(8)  NOT NULL,
            to_contract      VARCHAR(8)  NOT NULL,
            roll_date        DATE        NOT NULL,
            detection_method VARCHAR(20) NOT NULL,
            created_at       TIMESTAMP,
            updated_at       TIMESTAMP,
            PRIMARY KEY (id)
        )
    """)
    op.execute("CREATE INDEX IF NOT EXISTS idx_fr_symbol_date ON futures_rollovers (symbol, roll_date)")
    op.execute("CREATE UNIQUE INDEX IF NOT EXISTS idx_fr_symbol_from ON futures_rollovers (symbol, from_contract)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_futures_rollovers_id ON futures_rollovers (id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_futures_rollovers_roll_date ON futures_rollovers (roll_date)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_futures_rollovers_symbol ON futures_rollovers (symbol)")

    # ── journal_entries ──────────────────────────────────────────────────────
    # Note: no inline UNIQUE on entry_date — SQLAlchemy models declare this
    # via index=True + unique=True, which becomes a unique *index*, not a
    # standalone constraint.  A standalone constraint would cause alembic check
    # to flag a drift.
    op.execute("""
        CREATE TABLE IF NOT EXISTS journal_entries (
            id          SERIAL      NOT NULL,
            entry_date  DATE        NOT NULL,
            content     TEXT        NOT NULL,
            sentiment   VARCHAR(20),
            created_at  TIMESTAMP,
            updated_at  TIMESTAMP,
            PRIMARY KEY (id)
        )
    """)
    op.execute("CREATE UNIQUE INDEX IF NOT EXISTS ix_journal_entries_entry_date ON journal_entries (entry_date)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_journal_entries_id ON journal_entries (id)")

    # ── tags ─────────────────────────────────────────────────────────────────
    # Same: name uniqueness is expressed as a unique index, not a constraint.
    op.execute("""
        CREATE TABLE IF NOT EXISTS tags (
            id    SERIAL      NOT NULL,
            name  VARCHAR(50) NOT NULL,
            color VARCHAR(20),
            PRIMARY KEY (id)
        )
    """)
    op.execute("CREATE INDEX IF NOT EXISTS ix_tags_id ON tags (id)")
    op.execute("CREATE UNIQUE INDEX IF NOT EXISTS ix_tags_name ON tags (name)")

    # ── stock_metrics ────────────────────────────────────────────────────────
    op.execute("""
        CREATE TABLE IF NOT EXISTS stock_metrics (
            ticker          VARCHAR NOT NULL REFERENCES ticker_references (ticker),
            date            DATE    NOT NULL,
            close_price     FLOAT,
            volume          FLOAT,
            avg_volume_30d  FLOAT,
            sma_50          FLOAT,
            sma_200         FLOAT,
            high_52w        FLOAT,
            low_52w         FLOAT,
            atr_14          FLOAT,
            PRIMARY KEY (ticker, date)
        )
    """)
    op.execute("CREATE INDEX IF NOT EXISTS ix_stock_metrics_date ON stock_metrics (date)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_stock_metrics_ticker ON stock_metrics (ticker)")

    # ── trade_executions ─────────────────────────────────────────────────────
    op.execute("""
        CREATE TABLE IF NOT EXISTS trade_executions (
            id          SERIAL          NOT NULL,
            trade_id    INTEGER         REFERENCES trades (id) ON DELETE CASCADE,
            timestamp   TIMESTAMP       NOT NULL,
            side        VARCHAR(10)     NOT NULL,
            price       NUMERIC         NOT NULL,
            quantity    NUMERIC         NOT NULL,
            commission  NUMERIC,
            external_id VARCHAR(100),
            PRIMARY KEY (id)
        )
    """)
    op.execute("CREATE INDEX IF NOT EXISTS ix_trade_executions_external_id ON trade_executions (external_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_trade_executions_id ON trade_executions (id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_trade_executions_timestamp ON trade_executions (timestamp)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_trade_executions_trade_id ON trade_executions (trade_id)")

    # ── trade_tags (junction table) ──────────────────────────────────────────
    op.execute("""
        CREATE TABLE IF NOT EXISTS trade_tags (
            trade_id  INTEGER NOT NULL REFERENCES trades (id) ON DELETE CASCADE,
            tag_id    INTEGER NOT NULL REFERENCES tags (id)   ON DELETE CASCADE,
            PRIMARY KEY (trade_id, tag_id)
        )
    """)

    # ── indexes on pre-existing tables ───────────────────────────────────────
    op.execute("CREATE INDEX IF NOT EXISTS ix_market_holidays_id ON market_holidays (id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_ticker_references_ticker ON ticker_references (ticker)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_trades_close_date ON trades (close_date)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_trades_id ON trades (id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_trades_open_date ON trades (open_date)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_trades_side ON trades (side)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_trades_status ON trades (status)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_trades_symbol ON trades (symbol)")

    # ── universe_quality_reports: replace UNIQUE constraint with unique index ─
    # The model declares unique=True on the index column, which Alembic
    # represents as an index rather than a standalone constraint.
    # On production the constraint may already have been dropped; use DO $$
    # blocks to make the operations idempotent.
    op.execute("""
        DO $$
        BEGIN
            ALTER TABLE universe_quality_reports
                DROP CONSTRAINT IF EXISTS universe_quality_reports_universe_id_key;
        EXCEPTION WHEN others THEN
            NULL;
        END
        $$;
    """)
    op.execute("DROP INDEX IF EXISTS ix_universe_quality_reports_universe_id")
    op.execute("CREATE UNIQUE INDEX IF NOT EXISTS ix_universe_quality_reports_universe_id ON universe_quality_reports (universe_id)")


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS ix_universe_quality_reports_universe_id")
    op.execute("CREATE INDEX IF NOT EXISTS ix_universe_quality_reports_universe_id ON universe_quality_reports (universe_id)")
    op.execute("""
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM pg_constraint
                WHERE conname = 'universe_quality_reports_universe_id_key'
            ) THEN
                ALTER TABLE universe_quality_reports
                    ADD CONSTRAINT universe_quality_reports_universe_id_key
                    UNIQUE (universe_id);
            END IF;
        END
        $$;
    """)

    op.execute("DROP INDEX IF EXISTS ix_trades_symbol")
    op.execute("DROP INDEX IF EXISTS ix_trades_status")
    op.execute("DROP INDEX IF EXISTS ix_trades_side")
    op.execute("DROP INDEX IF EXISTS ix_trades_open_date")
    op.execute("DROP INDEX IF EXISTS ix_trades_id")
    op.execute("DROP INDEX IF EXISTS ix_trades_close_date")
    op.execute("DROP INDEX IF EXISTS ix_ticker_references_ticker")
    op.execute("DROP INDEX IF EXISTS ix_market_holidays_id")

    op.execute("DROP TABLE IF EXISTS trade_tags")

    op.execute("DROP INDEX IF EXISTS ix_trade_executions_trade_id")
    op.execute("DROP INDEX IF EXISTS ix_trade_executions_timestamp")
    op.execute("DROP INDEX IF EXISTS ix_trade_executions_id")
    op.execute("DROP INDEX IF EXISTS ix_trade_executions_external_id")
    op.execute("DROP TABLE IF EXISTS trade_executions")

    op.execute("DROP INDEX IF EXISTS ix_stock_metrics_ticker")
    op.execute("DROP INDEX IF EXISTS ix_stock_metrics_date")
    op.execute("DROP TABLE IF EXISTS stock_metrics")

    op.execute("DROP INDEX IF EXISTS ix_tags_name")
    op.execute("DROP INDEX IF EXISTS ix_tags_id")
    op.execute("DROP TABLE IF EXISTS tags")

    op.execute("DROP INDEX IF EXISTS ix_journal_entries_id")
    op.execute("DROP INDEX IF EXISTS ix_journal_entries_entry_date")
    op.execute("DROP TABLE IF EXISTS journal_entries")

    op.execute("DROP INDEX IF EXISTS ix_futures_rollovers_symbol")
    op.execute("DROP INDEX IF EXISTS ix_futures_rollovers_roll_date")
    op.execute("DROP INDEX IF EXISTS ix_futures_rollovers_id")
    op.execute("DROP INDEX IF EXISTS idx_fr_symbol_from")
    op.execute("DROP INDEX IF EXISTS idx_fr_symbol_date")
    op.execute("DROP TABLE IF EXISTS futures_rollovers")

    op.execute("DROP INDEX IF EXISTS ix_futures_contracts_symbol")
    op.execute("DROP INDEX IF EXISTS ix_futures_contracts_id")
    op.execute("DROP INDEX IF EXISTS idx_fc_symbol_month")
    op.execute("DROP INDEX IF EXISTS idx_fc_symbol_exchange")
    op.execute("DROP TABLE IF EXISTS futures_contracts")
