"""add_regime_models_and_scanner_event_regime

Revision ID: 395c7409c8e9
Revises: f7e8d9c0b1a2
Create Date: 2026-06-12 20:50:24.228656

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "395c7409c8e9"
down_revision: Union[str, None] = "f7e8d9c0b1a2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # This revision was restored only to preserve Alembic history for an
    # orphaned preview schema. The following migration removes that schema with
    # guarded drops, so clean databases must not require these objects to exist.
    pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "regime_models",
        sa.Column("training_rows", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "regime_models",
        sa.Column("error_message", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "regime_models",
        sa.Column(
            "completed_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "regime_models",
        sa.Column("model_artifact", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.drop_index(op.f("ix_regime_models_version"), table_name="regime_models")
    op.drop_index("ix_regime_models_status_version", table_name="regime_models")
    op.create_index(
        op.f("ix_regime_models_status"), "regime_models", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_regime_models_created_at"),
        "regime_models",
        ["created_at"],
        unique=False,
    )
    op.alter_column(
        "regime_models",
        "bic_score",
        existing_type=sa.Float(),
        type_=sa.VARCHAR(length=50),
        existing_nullable=True,
    )
    op.alter_column(
        "regime_models",
        "state_label_mapping",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    op.alter_column(
        "regime_models", "n_states", existing_type=sa.INTEGER(), nullable=True
    )
    op.drop_column("regime_models", "trained_at")
    op.drop_column("regime_models", "data_end_date")
    op.drop_column("regime_models", "data_start_date")
    op.drop_column("regime_models", "feature_set")
    op.drop_column("regime_models", "model_b64")
    # ### end Alembic commands ###
