"""add asset_class to universe models

Revision ID: 39cb3da5ccb4
Revises: b5f2c6389bb8
Create Date: 2026-04-06 09:31:28.298034

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "39cb3da5ccb4"
down_revision: Union[str, None] = "b5f2c6389bb8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop views that depend on monitored_stocks before altering columns
    op.execute("DROP VIEW IF EXISTS active_monitored_stocks")

    # Only keep asset_class and data_source changes
    op.add_column(
        "monitored_stocks",
        sa.Column(
            "asset_class", sa.String(length=50), server_default="stocks", nullable=False
        ),
    )
    op.add_column(
        "monitored_stocks",
        sa.Column(
            "data_source",
            sa.String(length=50),
            server_default="massive",
            nullable=False,
        ),
    )
    op.alter_column(
        "monitored_stocks",
        "market_cap",
        existing_type=sa.BIGINT(),
        type_=sa.Numeric(),
        existing_nullable=True,
    )
    op.alter_column(
        "monitored_stocks",
        "metadata",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=True,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.drop_index("idx_monitored_stocks_active", table_name="monitored_stocks")
    op.drop_index("idx_monitored_stocks_ticker", table_name="monitored_stocks")
    op.drop_index("idx_monitored_stocks_universe", table_name="monitored_stocks")
    op.create_index(
        op.f("ix_monitored_stocks_asset_class"),
        "monitored_stocks",
        ["asset_class"],
        unique=False,
    )
    op.create_index(
        op.f("ix_monitored_stocks_id"), "monitored_stocks", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_monitored_stocks_is_active"),
        "monitored_stocks",
        ["is_active"],
        unique=False,
    )
    op.create_index(
        op.f("ix_monitored_stocks_ticker"), "monitored_stocks", ["ticker"], unique=False
    )
    op.create_index(
        op.f("ix_monitored_stocks_universe_id"),
        "monitored_stocks",
        ["universe_id"],
        unique=False,
    )
    op.drop_constraint(
        "monitored_stocks_universe_id_fkey", "monitored_stocks", type_="foreignkey"
    )
    op.alter_column(
        "news_articles",
        "tickers",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        type_=sa.JSON().with_variant(
            postgresql.JSONB(astext_type=sa.Text()), "postgresql"
        ),
        existing_nullable=True,
    )
    op.alter_column(
        "scanner_configs",
        "parameters",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=False,
    )
    op.alter_column(
        "scanner_configs",
        "criteria",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=False,
    )
    op.drop_constraint("scanner_configs_uuid_key", "scanner_configs", type_="unique")
    op.create_index(
        op.f("ix_scanner_configs_id"), "scanner_configs", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_scanner_configs_uuid"), "scanner_configs", ["uuid"], unique=True
    )
    op.drop_column("scanner_configs", "created_by")
    op.alter_column(
        "scanner_events",
        "indicators",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
    )
    op.alter_column(
        "scanner_events",
        "criteria_met",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
    )
    op.alter_column(
        "scanner_events",
        "metadata",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
    )
    op.add_column(
        "stock_universe_tickers",
        sa.Column(
            "asset_class", sa.String(length=50), server_default="stocks", nullable=False
        ),
    )
    # Corrected name to 'data_source' as in models
    op.add_column(
        "stock_universe_tickers",
        sa.Column(
            "data_source",
            sa.String(length=50),
            server_default="massive",
            nullable=False,
        ),
    )
    op.alter_column(
        "stock_universes",
        "criteria",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=False,
    )
    op.drop_constraint("stock_universes_uuid_key", "stock_universes", type_="unique")
    op.create_index(
        op.f("ix_stock_universes_id"), "stock_universes", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_stock_universes_uuid"), "stock_universes", ["uuid"], unique=True
    )
    op.drop_column("stock_universes", "created_by")

    # Re-create the view
    op.execute(
        "CREATE VIEW active_monitored_stocks AS SELECT * FROM monitored_stocks WHERE is_active = true"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "stock_universes",
        sa.Column(
            "created_by",
            sa.VARCHAR(length=100),
            server_default=sa.text("'system'::character varying"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_index(op.f("ix_stock_universes_uuid"), table_name="stock_universes")
    op.drop_index(op.f("ix_stock_universes_id"), table_name="stock_universes")
    op.create_unique_constraint("stock_universes_uuid_key", "stock_universes", ["uuid"])
    op.alter_column(
        "stock_universes",
        "criteria",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
    )
    op.drop_column("stock_universe_tickers", "data_source")
    op.drop_column("stock_universe_tickers", "asset_class")
    op.alter_column(
        "scanner_events",
        "metadata",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=postgresql.JSON(astext_type=sa.Text()),
        existing_nullable=False,
    )
    op.alter_column(
        "scanner_events",
        "criteria_met",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=postgresql.JSON(astext_type=sa.Text()),
        existing_nullable=False,
    )
    op.alter_column(
        "scanner_events",
        "indicators",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=postgresql.JSON(astext_type=sa.Text()),
        existing_nullable=False,
    )
    op.add_column(
        "scanner_configs",
        sa.Column(
            "created_by",
            sa.VARCHAR(length=100),
            server_default=sa.text("'system'::character varying"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_index(op.f("ix_scanner_configs_uuid"), table_name="scanner_configs")
    op.drop_index(op.f("ix_scanner_configs_id"), table_name="scanner_configs")
    op.create_unique_constraint("scanner_configs_uuid_key", "scanner_configs", ["uuid"])
    op.alter_column(
        "scanner_configs",
        "criteria",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
    )
    op.alter_column(
        "scanner_configs",
        "parameters",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
    )
    op.alter_column(
        "news_articles",
        "tickers",
        existing_type=sa.JSON().with_variant(
            postgresql.JSONB(astext_type=sa.Text()), "postgresql"
        ),
        type_=postgresql.JSON(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.create_foreign_key(
        "monitored_stocks_universe_id_fkey",
        "monitored_stocks",
        "stock_universes",
        ["universe_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_index(
        op.f("ix_monitored_stocks_universe_id"), table_name="monitored_stocks"
    )
    op.drop_index(op.f("ix_monitored_stocks_ticker"), table_name="monitored_stocks")
    op.drop_index(op.f("ix_monitored_stocks_is_active"), table_name="monitored_stocks")
    op.drop_index(op.f("ix_monitored_stocks_id"), table_name="monitored_stocks")
    op.drop_index(
        op.f("ix_monitored_stocks_asset_class"), table_name="monitored_stocks"
    )
    op.create_index(
        "idx_monitored_stocks_universe",
        "monitored_stocks",
        ["universe_id"],
        unique=False,
    )
    op.create_index(
        "idx_monitored_stocks_ticker", "monitored_stocks", ["ticker"], unique=False
    )
    op.create_index(
        "idx_monitored_stocks_active", "monitored_stocks", ["is_active"], unique=False
    )
    op.alter_column(
        "monitored_stocks",
        "metadata",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.alter_column(
        "monitored_stocks",
        "market_cap",
        existing_type=sa.Numeric(),
        type_=sa.BIGINT(),
        existing_nullable=True,
    )
    op.drop_column("monitored_stocks", "data_source")
    op.drop_column("monitored_stocks", "asset_class")
    op.create_table(
        "alert_history",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "uuid",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("alert_config_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("volume_event_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "alert_type", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
        sa.Column("ticker", sa.VARCHAR(length=10), autoincrement=False, nullable=False),
        sa.Column(
            "alert_date", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "delivery_status",
            sa.VARCHAR(length=20),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "delivery_attempts",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "last_attempt", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "response_data",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("error_message", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["alert_config_id"],
            ["alert_configs.id"],
            name="alert_history_alert_config_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="alert_history_pkey"),
        sa.UniqueConstraint("uuid", name="alert_history_uuid_key"),
    )
    op.create_table(
        "user_preferences",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "user_id", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
        sa.Column(
            "dashboard_layout",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "default_universe_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "alert_settings",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "notification_settings",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "theme",
            sa.VARCHAR(length=20),
            server_default=sa.text("'light'::character varying"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "language",
            sa.VARCHAR(length=10),
            server_default=sa.text("'en'::character varying"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["default_universe_id"],
            ["stock_universes.id"],
            name="user_preferences_default_universe_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id", name="user_preferences_pkey"),
    )
    op.create_table(
        "scanner_execution_log",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "uuid",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "scanner_config_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "execution_type", sa.VARCHAR(length=20), autoincrement=False, nullable=False
        ),
        sa.Column(
            "start_time", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "end_time", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "stocks_scanned",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "events_detected",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "errors_encountered",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "execution_duration_ms", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column("memory_usage_mb", sa.NUMERIC(), autoincrement=False, nullable=True),
        sa.Column("status", sa.VARCHAR(length=20), autoincrement=False, nullable=False),
        sa.Column("error_log", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["scanner_config_id"],
            ["scanner_configs.id"],
            name="scanner_execution_log_scanner_config_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="scanner_execution_log_pkey"),
        sa.UniqueConstraint("uuid", name="scanner_execution_log_uuid_key"),
    )
    op.create_index(
        "idx_scanner_execution_log_status",
        "scanner_execution_log",
        ["status"],
        unique=False,
    )
    op.create_index(
        "idx_scanner_execution_log_start_time",
        "scanner_execution_log",
        ["start_time"],
        unique=False,
    )
    op.create_table(
        "market_data_cache",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("ticker", sa.VARCHAR(length=10), autoincrement=False, nullable=False),
        sa.Column(
            "data_type", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
        sa.Column(
            "data",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "data_hash", sa.VARCHAR(length=64), autoincrement=False, nullable=False
        ),
        sa.Column(
            "expires_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "last_accessed",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "access_count",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name="market_data_cache_pkey"),
    )
    op.create_index(
        "idx_market_data_cache_type", "market_data_cache", ["data_type"], unique=False
    )
    op.create_index(
        "idx_market_data_cache_ticker", "market_data_cache", ["ticker"], unique=False
    )
    op.create_index(
        "idx_market_data_cache_expires",
        "market_data_cache",
        ["expires_at"],
        unique=False,
    )
    op.create_table(
        "alert_configs",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "uuid",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("name", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "alert_type", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
        sa.Column(
            "conditions",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "delivery_method",
            sa.VARCHAR(length=50),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "delivery_config",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "is_active",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_by",
            sa.VARCHAR(length=100),
            server_default=sa.text("'system'::character varying"),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name="alert_configs_pkey"),
        sa.UniqueConstraint("uuid", name="alert_configs_uuid_key"),
    )
    # ### end Alembic commands ###
