"""Initial_migration

Revision ID: 4565663382ae
Revises: 
Create Date: 2025-12-14 16:16:16.211816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4565663382ae'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_scanner_execution_log_start_time', table_name='scanner_execution_log')
    op.drop_index('idx_scanner_execution_log_status', table_name='scanner_execution_log')
    op.drop_table('scanner_execution_log')
    op.drop_table('alert_history')
    op.drop_table('stock_universes')
    op.drop_table('user_preferences')
    op.drop_index('ix_stock_metrics_date', table_name='stock_metrics')
    op.drop_index('ix_stock_metrics_ticker', table_name='stock_metrics')
    op.drop_table('stock_metrics')
    op.drop_index('idx_monitored_stocks_active', table_name='monitored_stocks')
    op.drop_index('idx_monitored_stocks_ticker', table_name='monitored_stocks')
    op.drop_index('idx_monitored_stocks_universe', table_name='monitored_stocks')
    op.drop_table('monitored_stocks')
    op.drop_index('idx_volume_events_date', table_name='volume_events')
    op.drop_index('idx_volume_events_relative_vol', table_name='volume_events')
    op.drop_index('idx_volume_events_ticker', table_name='volume_events')
    op.drop_index('idx_volume_events_type', table_name='volume_events')
    op.drop_table('volume_events')
    op.drop_table('alert_configs')
    op.drop_index('ix_ticker_references_ticker', table_name='ticker_references')
    op.drop_table('ticker_references')
    op.drop_table('scanner_configs')
    op.drop_index('idx_market_data_cache_expires', table_name='market_data_cache')
    op.drop_index('idx_market_data_cache_ticker', table_name='market_data_cache')
    op.drop_index('idx_market_data_cache_type', table_name='market_data_cache')
    op.drop_table('market_data_cache')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_data_cache',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('data_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('data_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('last_accessed', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('access_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='market_data_cache_pkey')
    )
    op.create_index('idx_market_data_cache_type', 'market_data_cache', ['data_type'], unique=False)
    op.create_index('idx_market_data_cache_ticker', 'market_data_cache', ['ticker'], unique=False)
    op.create_index('idx_market_data_cache_expires', 'market_data_cache', ['expires_at'], unique=False)
    op.create_table('scanner_configs',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('scanner_configs_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('scanner_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('criteria', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('run_frequency', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('last_run', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('next_run', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=100), server_default=sa.text("'system'::character varying"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='scanner_configs_pkey'),
    sa.UniqueConstraint('uuid', name='scanner_configs_uuid_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('ticker_references',
    sa.Column('ticker', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('market_cap', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('outstanding_shares', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sector', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('industry', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('last_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('primary_exchange', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('list_date', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('total_employees', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('share_class_shares_outstanding', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('weighted_shares_outstanding', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sic_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sic_description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('homepage_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('last_details_update', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('ticker', name='ticker_references_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_ticker_references_ticker', 'ticker_references', ['ticker'], unique=False)
    op.create_table('alert_configs',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('alert_configs_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('alert_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('delivery_method', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('delivery_config', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=100), server_default=sa.text("'system'::character varying"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='alert_configs_pkey'),
    sa.UniqueConstraint('uuid', name='alert_configs_uuid_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('volume_events',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('volume_events_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=True),
    sa.Column('ticker', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('event_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('pre_market_volume', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('regular_volume', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('avg_volume_20d', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('avg_volume_50d', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('relative_volume', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('volume_spike_ratio', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('previous_close', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('pre_market_high', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('pre_market_low', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('opening_price', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('closing_price', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('price_change_pct', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('price_gap_pct', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('criteria_met', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('news_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('earnings_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('market_cap_at_event', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='volume_events_pkey'),
    sa.UniqueConstraint('uuid', name='volume_events_uuid_key'),
    postgresql_ignore_search_path=False
    )
    op.create_index('idx_volume_events_type', 'volume_events', ['event_type'], unique=False)
    op.create_index('idx_volume_events_ticker', 'volume_events', ['ticker'], unique=False)
    op.create_index('idx_volume_events_relative_vol', 'volume_events', ['relative_volume'], unique=False)
    op.create_index('idx_volume_events_date', 'volume_events', ['event_date'], unique=False)
    op.create_table('monitored_stocks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('company_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('sector', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('industry', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('market_cap', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('universe_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('added_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('last_scanned', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('scan_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['universe_id'], ['stock_universes.id'], name='monitored_stocks_universe_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='monitored_stocks_pkey')
    )
    op.create_index('idx_monitored_stocks_universe', 'monitored_stocks', ['universe_id'], unique=False)
    op.create_index('idx_monitored_stocks_ticker', 'monitored_stocks', ['ticker'], unique=False)
    op.create_index('idx_monitored_stocks_active', 'monitored_stocks', ['is_active'], unique=False)
    op.create_table('stock_metrics',
    sa.Column('ticker', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('close_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('volume', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('avg_volume_30d', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sma_50', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sma_200', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('high_52w', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('low_52w', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('atr_14', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ticker'], ['ticker_references.ticker'], name='stock_metrics_ticker_fkey'),
    sa.PrimaryKeyConstraint('ticker', 'date', name='stock_metrics_pkey')
    )
    op.create_index('ix_stock_metrics_ticker', 'stock_metrics', ['ticker'], unique=False)
    op.create_index('ix_stock_metrics_date', 'stock_metrics', ['date'], unique=False)
    op.create_table('user_preferences',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('dashboard_layout', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('default_universe_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('alert_settings', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('notification_settings', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('theme', sa.VARCHAR(length=20), server_default=sa.text("'light'::character varying"), autoincrement=False, nullable=True),
    sa.Column('language', sa.VARCHAR(length=10), server_default=sa.text("'en'::character varying"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['default_universe_id'], ['stock_universes.id'], name='user_preferences_default_universe_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_preferences_pkey')
    )
    op.create_table('stock_universes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('criteria', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=100), server_default=sa.text("'system'::character varying"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='stock_universes_pkey'),
    sa.UniqueConstraint('uuid', name='stock_universes_uuid_key')
    )
    op.create_table('alert_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=True),
    sa.Column('alert_config_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('volume_event_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('alert_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('ticker', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('alert_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('delivery_status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('delivery_attempts', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('last_attempt', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('response_data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['alert_config_id'], ['alert_configs.id'], name='alert_history_alert_config_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['volume_event_id'], ['volume_events.id'], name='alert_history_volume_event_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='alert_history_pkey'),
    sa.UniqueConstraint('uuid', name='alert_history_uuid_key')
    )
    op.create_table('scanner_execution_log',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=True),
    sa.Column('scanner_config_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('execution_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('end_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('stocks_scanned', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('events_detected', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('errors_encountered', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('execution_duration_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('memory_usage_mb', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('error_log', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['scanner_config_id'], ['scanner_configs.id'], name='scanner_execution_log_scanner_config_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='scanner_execution_log_pkey'),
    sa.UniqueConstraint('uuid', name='scanner_execution_log_uuid_key')
    )
    op.create_index('idx_scanner_execution_log_status', 'scanner_execution_log', ['status'], unique=False)
    op.create_index('idx_scanner_execution_log_start_time', 'scanner_execution_log', ['start_time'], unique=False)
    # ### end Alembic commands ###
