"""add_tweet_monitor_tables

Revision ID: 48f7ed85ea81
Revises: c1d2e3f4a5b6
Create Date: 2026-05-26 00:16:22.697177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '48f7ed85ea81'
down_revision: Union[str, None] = 'c1d2e3f4a5b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monitored_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('handle', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('poll_interval_seconds', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('classification_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_poll_at', sa.DateTime(), nullable=True),
    sa.Column('last_tweet_id', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('handle', 'platform', name='uq_monitored_account_handle_platform')
    )
    op.create_index(op.f('ix_monitored_accounts_id'), 'monitored_accounts', ['id'], unique=False)
    op.create_table('tweet_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('tweet_id', sa.String(length=30), nullable=False),
    sa.Column('tweet_url', sa.String(length=200), nullable=False),
    sa.Column('posted_at', sa.DateTime(), nullable=False),
    sa.Column('scraped_at', sa.DateTime(), nullable=True),
    sa.Column('full_text', sa.Text(), nullable=False),
    sa.Column('media_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('classification', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('tickers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('price_levels', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=True),
    sa.Column('promoted', sa.Boolean(), nullable=False),
    sa.Column('scanner_event_id', sa.Integer(), nullable=True),
    sa.Column('promotion_reason', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['monitored_accounts.id'], ),
    sa.ForeignKeyConstraint(['scanner_event_id'], ['scanner_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tweet_signals_account_id'), 'tweet_signals', ['account_id'], unique=False)
    op.create_index('ix_tweet_signals_account_posted', 'tweet_signals', ['account_id', 'posted_at'], unique=False)
    op.create_index('ix_tweet_signals_classification_confidence', 'tweet_signals', ['classification', 'confidence'], unique=False)
    op.create_index(op.f('ix_tweet_signals_id'), 'tweet_signals', ['id'], unique=False)
    op.create_index('ix_tweet_signals_promoted_classification', 'tweet_signals', ['promoted', 'classification'], unique=False)
    op.create_index(op.f('ix_tweet_signals_tweet_id'), 'tweet_signals', ['tweet_id'], unique=True)
    op.drop_table('alert_history')
    op.drop_table('alert_configs')
    op.execute('DROP VIEW IF EXISTS scanner_performance_stats')
    op.drop_index(op.f('idx_scanner_execution_log_start_time'), table_name='scanner_execution_log')
    op.drop_index(op.f('idx_scanner_execution_log_status'), table_name='scanner_execution_log')
    op.drop_table('scanner_execution_log')
    op.drop_table('user_preferences')
    op.drop_index(op.f('idx_market_data_cache_expires'), table_name='market_data_cache')
    op.drop_index(op.f('idx_market_data_cache_ticker'), table_name='market_data_cache')
    op.drop_index(op.f('idx_market_data_cache_type'), table_name='market_data_cache')
    op.drop_table('market_data_cache')
    op.drop_index(op.f('idx_scanner_events_score'), table_name='scanner_events')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_scanner_events_score'), 'scanner_events', [sa.literal_column('signal_quality_score DESC NULLS LAST')], unique=False)
    op.create_table('market_data_cache',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('data_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('data_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('last_accessed', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('access_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('market_data_cache_pkey'))
    )
    op.create_index(op.f('idx_market_data_cache_type'), 'market_data_cache', ['data_type'], unique=False)
    op.create_index(op.f('idx_market_data_cache_ticker'), 'market_data_cache', ['ticker'], unique=False)
    op.create_index(op.f('idx_market_data_cache_expires'), 'market_data_cache', ['expires_at'], unique=False)
    op.create_table('user_preferences',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('dashboard_layout', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('default_universe_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('alert_settings', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('notification_settings', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('theme', sa.VARCHAR(length=20), server_default=sa.text("'light'::character varying"), autoincrement=False, nullable=True),
    sa.Column('language', sa.VARCHAR(length=10), server_default=sa.text("'en'::character varying"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['default_universe_id'], ['stock_universes.id'], name=op.f('user_preferences_default_universe_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_preferences_pkey'))
    )
    op.create_table('alert_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=True),
    sa.Column('alert_config_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('volume_event_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('alert_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('ticker', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('alert_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('delivery_status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('delivery_attempts', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('last_attempt', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('response_data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['alert_config_id'], ['alert_configs.id'], name=op.f('alert_history_alert_config_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('alert_history_pkey')),
    sa.UniqueConstraint('uuid', name=op.f('alert_history_uuid_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('scanner_execution_log',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=True),
    sa.Column('scanner_config_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('execution_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('end_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('stocks_scanned', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('events_detected', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('errors_encountered', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('execution_duration_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('memory_usage_mb', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('error_log', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['scanner_config_id'], ['scanner_configs.id'], name=op.f('scanner_execution_log_scanner_config_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('scanner_execution_log_pkey')),
    sa.UniqueConstraint('uuid', name=op.f('scanner_execution_log_uuid_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_scanner_execution_log_status'), 'scanner_execution_log', ['status'], unique=False)
    op.create_index(op.f('idx_scanner_execution_log_start_time'), 'scanner_execution_log', ['start_time'], unique=False)
    op.create_table('alert_configs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('alert_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('delivery_method', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('delivery_config', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=100), server_default=sa.text("'system'::character varying"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('alert_configs_pkey')),
    sa.UniqueConstraint('uuid', name=op.f('alert_configs_uuid_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_index(op.f('ix_tweet_signals_tweet_id'), table_name='tweet_signals')
    op.drop_index('ix_tweet_signals_promoted_classification', table_name='tweet_signals')
    op.drop_index(op.f('ix_tweet_signals_id'), table_name='tweet_signals')
    op.drop_index('ix_tweet_signals_classification_confidence', table_name='tweet_signals')
    op.drop_index('ix_tweet_signals_account_posted', table_name='tweet_signals')
    op.drop_index(op.f('ix_tweet_signals_account_id'), table_name='tweet_signals')
    op.drop_table('tweet_signals')
    op.drop_index(op.f('ix_monitored_accounts_id'), table_name='monitored_accounts')
    op.drop_table('monitored_accounts')
    # ### end Alembic commands ###
