"""Add idx_fa_continuous_series index

Revision ID: 5b1f209e0188
Revises: c5d6e7f8a9b0
Create Date: 2026-04-09 21:10:12.983391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5b1f209e0188'
down_revision: Union[str, None] = 'c5d6e7f8a9b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_fa_continuous_series', 'futures_aggregates', ['symbol', 'timespan', 'multiplier', 'timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_fa_continuous_series', table_name='futures_aggregates')
    # ### end Alembic commands ###
    # ### end Alembic commands ###
