"""Add idx_fa_continuous_series index

Revision ID: 5b1f209e0188
Revises: c5d6e7f8a9b0
Create Date: 2026-04-09 21:10:12.983391

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5b1f209e0188"
down_revision: Union[str, None] = "c5d6e7f8a9b0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Ensure pre-Alembic table exists before adding index
    op.execute("""
        CREATE TABLE IF NOT EXISTS futures_aggregates (
            id SERIAL PRIMARY KEY,
            symbol VARCHAR(20) NOT NULL,
            contract_month VARCHAR(8) NOT NULL,
            exchange VARCHAR(20) NOT NULL,
            timestamp TIMESTAMP NOT NULL,
            timespan VARCHAR(20) NOT NULL DEFAULT 'day',
            multiplier INTEGER NOT NULL DEFAULT 1,
            open NUMERIC NOT NULL,
            high NUMERIC NOT NULL,
            low NUMERIC NOT NULL,
            close NUMERIC NOT NULL,
            volume BIGINT NOT NULL,
            vwap NUMERIC,
            transactions INTEGER,
            source VARCHAR(20) DEFAULT 'ibkr',
            created_at TIMESTAMP
        )
    """)
    op.execute("CREATE INDEX IF NOT EXISTS ix_futures_aggregates_id ON futures_aggregates (id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_futures_aggregates_symbol ON futures_aggregates (symbol)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_futures_aggregates_contract_month ON futures_aggregates (contract_month)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_futures_aggregates_timestamp ON futures_aggregates (timestamp)")
    op.execute("CREATE INDEX IF NOT EXISTS idx_fa_symbol_ts ON futures_aggregates (symbol, timestamp)")
    op.execute("CREATE INDEX IF NOT EXISTS idx_fa_symbol_contract ON futures_aggregates (symbol, contract_month)")
    op.execute("CREATE INDEX IF NOT EXISTS idx_fa_contract_ts ON futures_aggregates (symbol, contract_month, timestamp)")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "idx_fa_continuous_series",
        "futures_aggregates",
        ["symbol", "timespan", "multiplier", "timestamp"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_fa_continuous_series", table_name="futures_aggregates")
    # ### end Alembic commands ###
    # ### end Alembic commands ###
