"""add_signal_analysis_tables

Revision ID: 7ba47256a679
Revises: b1c2d3e4f5a6
Create Date: 2026-05-21 17:10:43.595250

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7ba47256a679"
down_revision: Union[str, None] = "b1c2d3e4f5a6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "signal_analysis_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("scanner_type", sa.String(length=50), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("event_count", sa.Integer(), nullable=True),
        sa.Column(
            "correlation_matrix", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "feature_weights", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("celery_task_id", sa.String(length=255), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_signal_analysis_runs_created_at"),
        "signal_analysis_runs",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_signal_analysis_runs_id"), "signal_analysis_runs", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_signal_analysis_runs_scanner_type"),
        "signal_analysis_runs",
        ["scanner_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_signal_analysis_runs_status"),
        "signal_analysis_runs",
        ["status"],
        unique=False,
    )
    op.create_table(
        "signal_clusters",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("analysis_run_id", sa.Integer(), nullable=False),
        sa.Column("cluster_index", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(length=200), nullable=False),
        sa.Column("centroid", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "return_profile", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("event_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["analysis_run_id"],
            ["signal_analysis_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_signal_clusters_analysis_run_id",
        "signal_clusters",
        ["analysis_run_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_signal_clusters_id"), "signal_clusters", ["id"], unique=False
    )
    op.add_column(
        "scanner_events", sa.Column("signal_cluster_id", sa.Integer(), nullable=True)
    )
    op.create_index(
        op.f("ix_scanner_events_signal_cluster_id"),
        "scanner_events",
        ["signal_cluster_id"],
        unique=False,
    )
    op.create_foreign_key(
        None, "scanner_events", "signal_clusters", ["signal_cluster_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "scanner_events", type_="foreignkey")
    op.drop_index(
        op.f("ix_scanner_events_signal_cluster_id"), table_name="scanner_events"
    )
    op.drop_column("scanner_events", "signal_cluster_id")
    op.drop_index(op.f("ix_signal_clusters_id"), table_name="signal_clusters")
    op.drop_index("ix_signal_clusters_analysis_run_id", table_name="signal_clusters")
    op.drop_table("signal_clusters")
    op.drop_index(
        op.f("ix_signal_analysis_runs_status"), table_name="signal_analysis_runs"
    )
    op.drop_index(
        op.f("ix_signal_analysis_runs_scanner_type"), table_name="signal_analysis_runs"
    )
    op.drop_index(op.f("ix_signal_analysis_runs_id"), table_name="signal_analysis_runs")
    op.drop_index(
        op.f("ix_signal_analysis_runs_created_at"), table_name="signal_analysis_runs"
    )
    op.drop_table("signal_analysis_runs")
    # ### end Alembic commands ###
