"""Add news models

Revision ID: 9263d8fa019f
Revises: 529368159157
Create Date: 2026-03-23 08:07:54.263419

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9263d8fa019f"
down_revision: Union[str, None] = "529368159157"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "news_articles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.Uuid(), nullable=True),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("author", sa.String(length=200), nullable=True),
        sa.Column("published_utc", sa.DateTime(), nullable=False),
        sa.Column("article_url", sa.String(length=1000), nullable=False),
        sa.Column("image_url", sa.String(length=1000), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("provider", sa.String(length=100), nullable=True),
        sa.Column("tickers", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("article_url"),
    )
    op.create_index(op.f("ix_news_articles_id"), "news_articles", ["id"], unique=False)
    op.create_index(
        op.f("ix_news_articles_published_utc"),
        "news_articles",
        ["published_utc"],
        unique=False,
    )
    op.create_index(
        op.f("ix_news_articles_uuid"), "news_articles", ["uuid"], unique=True
    )

    op.create_table(
        "news_preferences",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.Uuid(), nullable=True),
        sa.Column("include_general_market", sa.Boolean(), nullable=True),
        sa.Column("tracked_tickers", sa.JSON(), nullable=True),
        sa.Column("tracked_universes", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_news_preferences_id"), "news_preferences", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_news_preferences_uuid"), "news_preferences", ["uuid"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_news_preferences_uuid"), table_name="news_preferences")
    op.drop_index(op.f("ix_news_preferences_id"), table_name="news_preferences")
    op.drop_table("news_preferences")
    op.drop_index(op.f("ix_news_articles_uuid"), table_name="news_articles")
    op.drop_index(op.f("ix_news_articles_published_utc"), table_name="news_articles")
    op.drop_index(op.f("ix_news_articles_id"), table_name="news_articles")
    op.drop_table("news_articles")
    # ### end Alembic commands ###
