"""Refine idx_fa_continuous_series index

Revision ID: ccfae364a978
Revises: 5b1f209e0188
Create Date: 2026-04-09 21:16:18.402282

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ccfae364a978"
down_revision: Union[str, None] = "5b1f209e0188"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_fa_continuous_series", table_name="futures_aggregates")
    op.create_index(
        "idx_fa_continuous_series",
        "futures_aggregates",
        ["symbol", "contract_month", "timespan", "multiplier", "timestamp"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_fa_continuous_series", table_name="futures_aggregates")
    op.create_index(
        "idx_fa_continuous_series",
        "futures_aggregates",
        ["symbol", "timespan", "multiplier", "timestamp"],
        unique=False,
    )
    # ### end Alembic commands ###
    # ### end Alembic commands ###
