"""Add_ticker_fields

Revision ID: dd23e308d7c0
Revises:
Create Date: 2025-12-15 12:07:19.802834

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dd23e308d7c0"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Manual edit: Only adding ticker_references fields
    op.add_column("ticker_references", sa.Column("active", sa.Boolean(), nullable=True))
    op.add_column("ticker_references", sa.Column("cik", sa.String(), nullable=True))
    op.add_column(
        "ticker_references", sa.Column("composite_figi", sa.String(), nullable=True)
    )
    op.add_column("ticker_references", sa.Column("market", sa.String(), nullable=True))
    op.add_column("ticker_references", sa.Column("type", sa.String(), nullable=True))
    # Autogenerated detected change in description type (Text -> String or vice versa), keeping it to be safe
    # Actually description is defined as String in model but was TEXT in DB?
    # String usually maps to VARCHAR. TEXT is better for description.
    # The model has Column(String, nullable=True). In PG String without length is VARCHAR/TEXT.
    # The autogenerate wanted to change TEXT to String. Let's allowing it so schema stays in sync.
    op.alter_column(
        "ticker_references",
        "description",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=True,
    )


def downgrade() -> None:
    op.alter_column(
        "ticker_references",
        "description",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.drop_column("ticker_references", "type")
    op.drop_column("ticker_references", "market")
    op.drop_column("ticker_references", "composite_figi")
    op.drop_column("ticker_references", "cik")
    op.drop_column("ticker_references", "active")
