"""add_alerting_tables

Revision ID: f33989688da3
Revises: 7cc4463907cd
Create Date: 2026-04-12 16:00:13.727646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f33989688da3'
down_revision: Union[str, None] = '7cc4463907cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('scanner_types', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('severity_filter', sa.String(length=10), nullable=False),
    sa.Column('cooldown_minutes', sa.Integer(), nullable=False),
    sa.Column('channels', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('channel_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_rules_id'), 'alert_rules', ['id'], unique=False)
    op.create_table('push_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('p256dh', sa.Text(), nullable=False),
    sa.Column('auth', sa.Text(), nullable=False),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_push_subscriptions_endpoint'), 'push_subscriptions', ['endpoint'], unique=True)
    op.create_index(op.f('ix_push_subscriptions_id'), 'push_subscriptions', ['id'], unique=False)
    op.create_table('alert_delivery_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=True),
    sa.Column('scanner_event_id', sa.Integer(), nullable=True),
    sa.Column('ticker', sa.String(length=10), nullable=True),
    sa.Column('scanner_type', sa.String(length=50), nullable=True),
    sa.Column('channel', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['alert_rules.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scanner_event_id'], ['scanner_events.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_delivery_logs_id'), 'alert_delivery_logs', ['id'], unique=False)
    op.create_index(op.f('ix_alert_delivery_logs_rule_id'), 'alert_delivery_logs', ['rule_id'], unique=False)
    op.create_index(op.f('ix_alert_delivery_logs_scanner_event_id'), 'alert_delivery_logs', ['scanner_event_id'], unique=False)
    op.create_index(op.f('ix_alert_delivery_logs_ticker'), 'alert_delivery_logs', ['ticker'], unique=False)
    op.alter_column('monitored_stocks', 'asset_class',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'stocks'::character varying"))
    op.alter_column('monitored_stocks', 'data_source',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'massive'::character varying"))
    op.create_index(op.f('ix_monitored_stocks_data_source'), 'monitored_stocks', ['data_source'], unique=False)
    # ### end Alembic commands ###



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_monitored_stocks_data_source'), table_name='monitored_stocks')
    op.alter_column('monitored_stocks', 'data_source',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'massive'::character varying"))
    op.alter_column('monitored_stocks', 'asset_class',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'stocks'::character varying"))
    op.create_table('alert_configs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('alert_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('delivery_method', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('delivery_config', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=100), server_default=sa.text("'system'::character varying"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('alert_configs_pkey')),
    sa.UniqueConstraint('uuid', name=op.f('alert_configs_uuid_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('user_preferences',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('dashboard_layout', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('default_universe_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('alert_settings', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('notification_settings', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('theme', sa.VARCHAR(length=20), server_default=sa.text("'light'::character varying"), autoincrement=False, nullable=True),
    sa.Column('language', sa.VARCHAR(length=10), server_default=sa.text("'en'::character varying"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['default_universe_id'], ['stock_universes.id'], name=op.f('user_preferences_default_universe_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_preferences_pkey'))
    )
    op.create_table('alert_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=True),
    sa.Column('alert_config_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('volume_event_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('alert_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('ticker', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('alert_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('delivery_status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('delivery_attempts', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('last_attempt', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('response_data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['alert_config_id'], ['alert_configs.id'], name=op.f('alert_history_alert_config_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('alert_history_pkey')),
    sa.UniqueConstraint('uuid', name=op.f('alert_history_uuid_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('market_data_cache',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('data_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('data_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('last_accessed', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('access_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('market_data_cache_pkey'))
    )
    op.create_index(op.f('idx_market_data_cache_type'), 'market_data_cache', ['data_type'], unique=False)
    op.create_index(op.f('idx_market_data_cache_ticker'), 'market_data_cache', ['ticker'], unique=False)
    op.create_index(op.f('idx_market_data_cache_expires'), 'market_data_cache', ['expires_at'], unique=False)
    op.create_table('scanner_execution_log',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=True),
    sa.Column('scanner_config_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('execution_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('end_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('stocks_scanned', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('events_detected', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('errors_encountered', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('execution_duration_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('memory_usage_mb', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('error_log', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['scanner_config_id'], ['scanner_configs.id'], name=op.f('scanner_execution_log_scanner_config_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('scanner_execution_log_pkey')),
    sa.UniqueConstraint('uuid', name=op.f('scanner_execution_log_uuid_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_scanner_execution_log_status'), 'scanner_execution_log', ['status'], unique=False)
    op.create_index(op.f('idx_scanner_execution_log_start_time'), 'scanner_execution_log', ['start_time'], unique=False)
    op.drop_index(op.f('ix_alert_delivery_logs_ticker'), table_name='alert_delivery_logs')
    op.drop_index(op.f('ix_alert_delivery_logs_scanner_event_id'), table_name='alert_delivery_logs')
    op.drop_index(op.f('ix_alert_delivery_logs_rule_id'), table_name='alert_delivery_logs')
    op.drop_index(op.f('ix_alert_delivery_logs_id'), table_name='alert_delivery_logs')
    op.drop_table('alert_delivery_logs')
    op.drop_index(op.f('ix_push_subscriptions_id'), table_name='push_subscriptions')
    op.drop_index(op.f('ix_push_subscriptions_endpoint'), table_name='push_subscriptions')
    op.drop_table('push_subscriptions')
    op.drop_index(op.f('ix_alert_rules_id'), table_name='alert_rules')
    op.drop_table('alert_rules')
    # ### end Alembic commands ###
