"""add_scanner_runs_table

Revision ID: f652e7838258
Revises: f670d3191d9d
Create Date: 2026-03-29 15:55:28.656731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f652e7838258'
down_revision: Union[str, None] = 'f670d3191d9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scanner_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=True),
    sa.Column('scanner_type', sa.String(length=50), nullable=False),
    sa.Column('universe_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('stocks_scanned', sa.Integer(), nullable=True),
    sa.Column('events_detected', sa.Integer(), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['universe_id'], ['stock_universes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scanner_runs_id'), 'scanner_runs', ['id'], unique=False)
    op.create_index(op.f('ix_scanner_runs_uuid'), 'scanner_runs', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scanner_runs_uuid'), table_name='scanner_runs')
    op.drop_index(op.f('ix_scanner_runs_id'), table_name='scanner_runs')
    op.drop_table('scanner_runs')
    # ### end Alembic commands ###
