"""add_edge_metrics_to_volume_event

Revision ID: f670d3191d9d
Revises: da1b6d68ab9f
Create Date: 2026-03-29 10:35:16.418073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f670d3191d9d'
down_revision: Union[str, None] = 'da1b6d68ab9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('volume_events', sa.Column('regular_high', sa.Numeric(), nullable=True))
    op.add_column('volume_events', sa.Column('regular_low', sa.Numeric(), nullable=True))
    op.add_column('volume_events', sa.Column('post_market_high', sa.Numeric(), nullable=True))
    op.add_column('volume_events', sa.Column('post_market_low', sa.Numeric(), nullable=True))
    op.add_column('volume_events', sa.Column('total_day_high', sa.Numeric(), nullable=True))
    op.add_column('volume_events', sa.Column('total_day_low', sa.Numeric(), nullable=True))
    op.add_column('volume_events', sa.Column('fade_from_high_pct', sa.Numeric(), nullable=True))
    op.add_column('volume_events', sa.Column('day_range_pct', sa.Numeric(), nullable=True))
    op.add_column('volume_events', sa.Column('gap_pct', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('volume_events', 'gap_pct')
    op.drop_column('volume_events', 'day_range_pct')
    op.drop_column('volume_events', 'fade_from_high_pct')
    op.drop_column('volume_events', 'total_day_low')
    op.drop_column('volume_events', 'total_day_high')
    op.drop_column('volume_events', 'post_market_low')
    op.drop_column('volume_events', 'post_market_high')
    op.drop_column('volume_events', 'regular_low')
    op.drop_column('volume_events', 'regular_high')
    # ### end Alembic commands ###

