"""add_edge_metrics_to_volume_event

Revision ID: f670d3191d9d
Revises: da1b6d68ab9f
Create Date: 2026-03-29 10:35:16.418073

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f670d3191d9d"
down_revision: Union[str, None] = "da1b6d68ab9f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Ensure pre-Alembic table exists before adding columns
    op.execute("""
        CREATE TABLE IF NOT EXISTS volume_events (
            id SERIAL NOT NULL,
            uuid UUID DEFAULT gen_random_uuid(),
            ticker VARCHAR(10) NOT NULL,
            event_date DATE NOT NULL,
            event_type VARCHAR(50) NOT NULL,
            pre_market_volume BIGINT NOT NULL,
            regular_volume BIGINT,
            avg_volume_20d BIGINT NOT NULL,
            avg_volume_50d BIGINT,
            relative_volume NUMERIC NOT NULL,
            volume_spike_ratio NUMERIC NOT NULL,
            previous_close NUMERIC NOT NULL,
            pre_market_high NUMERIC,
            pre_market_low NUMERIC,
            opening_price NUMERIC,
            closing_price NUMERIC,
            price_change_pct NUMERIC,
            price_gap_pct NUMERIC,
            criteria_met JSONB NOT NULL,
            news_count INTEGER DEFAULT 0,
            earnings_date DATE,
            market_cap_at_event BIGINT,
            raw_data JSONB DEFAULT '{}'::jsonb,
            created_at TIMESTAMP DEFAULT now(),
            updated_at TIMESTAMP DEFAULT now(),
            CONSTRAINT volume_events_pkey PRIMARY KEY (id),
            CONSTRAINT volume_events_uuid_key UNIQUE (uuid)
        )
    """)
    op.execute("CREATE INDEX IF NOT EXISTS idx_volume_events_type ON volume_events (event_type)")
    op.execute("CREATE INDEX IF NOT EXISTS idx_volume_events_ticker ON volume_events (ticker)")
    op.execute("CREATE INDEX IF NOT EXISTS idx_volume_events_relative_vol ON volume_events (relative_volume)")
    op.execute("CREATE INDEX IF NOT EXISTS idx_volume_events_date ON volume_events (event_date)")

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "volume_events", sa.Column("regular_high", sa.Numeric(), nullable=True)
    )
    op.add_column(
        "volume_events", sa.Column("regular_low", sa.Numeric(), nullable=True)
    )
    op.add_column(
        "volume_events", sa.Column("post_market_high", sa.Numeric(), nullable=True)
    )
    op.add_column(
        "volume_events", sa.Column("post_market_low", sa.Numeric(), nullable=True)
    )
    op.add_column(
        "volume_events", sa.Column("total_day_high", sa.Numeric(), nullable=True)
    )
    op.add_column(
        "volume_events", sa.Column("total_day_low", sa.Numeric(), nullable=True)
    )
    op.add_column(
        "volume_events", sa.Column("fade_from_high_pct", sa.Numeric(), nullable=True)
    )
    op.add_column(
        "volume_events", sa.Column("day_range_pct", sa.Numeric(), nullable=True)
    )
    op.add_column("volume_events", sa.Column("gap_pct", sa.Numeric(), nullable=True))
    # ### end Alembic commands ###
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("volume_events", "gap_pct")
    op.drop_column("volume_events", "day_range_pct")
    op.drop_column("volume_events", "fade_from_high_pct")
    op.drop_column("volume_events", "total_day_low")
    op.drop_column("volume_events", "total_day_high")
    op.drop_column("volume_events", "post_market_low")
    op.drop_column("volume_events", "post_market_high")
    op.drop_column("volume_events", "regular_low")
    op.drop_column("volume_events", "regular_high")
    # ### end Alembic commands ###
